### PR TITLE
Return a set of ImplWitnesses from impl lookup

### PR DESCRIPTION
**Pull request by danakj**
A query facet type may contain multiple required interfaces, in which case impl lookup should return an ImplWitness for an impl that is used for each interface in the query. We bundle these together into an instruction block and return that from impl lookup. The witnesses are in the same order as the interfaces in the `CompleteFacetType::required_interfaces`. This allows walking the `required_interfaces` to find an interface to give an index that can also be used to grab a witness from this set, or from FacetValue.

FacetValue now has an InstBlockId for the set of witnesses of the FacetType, instead of a single ImplWitness instruction id.

FacetAccessWitness includes the index of the witness (determined from the position in `required_interfaces`) of the witness it's accessing from the FacetType.

The toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon test demonstrates the fix in the resulting SemIR. We can see the calls to methods on a multi-interface FacetType result in a FacetAccessWitness with an index of the correct interface, and this results in a witness that leads to the correct impl's function.

There is a TODO in member access, where it does not have a `CompleteFacetType` yet, so it uses the index in `FacetTypeInfo::impls_constraints` instead, but this can be incorrect in the presence of named constraints, which when completed can add more interfaces to the `CompleteFacetType` and which are sorted into an arbitrary order with the rest there.

### CODE REVIEW

**Comment by danakj** [comment]
This is rebased on https://github.com/carbon-language/carbon-lang/pull/5047, the last commit is the new content.

edit: now three commits.

edit: i have rebased back onto trunk

File: toolchain/check/impl_lookup.cpp [hunk 1]
```diff
@@ -373,29 +376,29 @@ auto LookupImplWitness(Context& context, SemIR::LocId loc_id,
...
     // TODO: Remove this when the context.TODO() is removed in
     // GetInterfacesFromConstantId.
-    return SemIR::InstId::None;
+    return SemIR::InstBlockId::None;
   }
   if (has_other_requirements) {
     // TODO: Remove this when other requirements go away.
-    return SemIR::InstId::None;
+    return SemIR::InstBlockId::None;
   }
```
Comment (josh11b) [inline toolchain/check/impl_lookup.cpp]: (This could be done in a follow-up, but this PR opens the door to fixing the issue.)

Also delete the `context.TODO(`...`)` call in `GetInterfacesFromConstantId`

```suggestion
  if (has_other_requirements) {
    // TODO: Remove this when other requirements go away.
    return SemIR::InstBlockId::None;
  }
  if (interfaces.empty()) {
    return SemIR::InstBlockId::Empty;
  }
```

File: toolchain/check/impl_lookup.h [hunk 2]
```diff
@@ -10,12 +10,27 @@
...
+//   the facet type is satisfied for the type in `type_const_id`, and provides a
+//   witness for accessing the impl of each interface.
+//
+// - `InstBlockId::None`, indicating lookup failed for at least one required
+//   interface in the `query_facet_type_const_id`. The facet type is not
+//   satisfied for the type in `type_const_id`.
+//
+// - An error value, indicating lookup failed and a diagonstic has been
+//   produced, either in this function or before.
+
```
Comment (josh11b) [inline toolchain/check/impl_lookup.h]:
```suggestion
```

File: toolchain/check/impl_lookup.h [hunk 3]
```diff
@@ -10,12 +10,27 @@
...
+// - A non-empty InstBlockId value, containing an `ImplWitness` instruction for
+//   each required interface in the `query_facet_type_const_id`. This verifies
+//   the facet type is satisfied for the type in `type_const_id`, and provides a
+//   witness for accessing the impl of each interface.
+//
+// - `InstBlockId::None`, indicating lookup failed for at least one required
+//   interface in the `query_facet_type_const_id`. The facet type is not
+//   satisfied for the type in `type_const_id`.
+//
+// - An error value, indicating lookup failed and a diagonstic has been
```
Comment (josh11b) [inline toolchain/check/impl_lookup.h]: Seems like `None` is saying "lookup failed find the full interface", and error is saying something more is wrong.

File: toolchain/check/impl_lookup.h [hunk 4]
```diff
@@ -10,12 +10,27 @@
...
 
-// Looks up the witness to use for a particular type and interface. Returns the
-// witness, or `InstId::None` if the type is not known to implement the
-// interface.
+// Looks up the witnesses to use for a particular type and a facet type naming a
+// set of interfaces required to be implemented for that type, as well as
+// possible constraints on those interfaces.
+//
+// The return value is one of:
+// - A non-empty InstBlockId value, containing an `ImplWitness` instruction for
```
Comment (josh11b) [inline toolchain/check/impl_lookup.h]:
```suggestion
// - An InstBlockId value, containing an `ImplWitness` instruction for
```

File: toolchain/check/member_access.cpp [hunk 5]
```diff
@@ -300,19 +313,24 @@ static auto LookupMemberNameInScope(Context& context, SemIR::LocId loc_id,
             context.facet_types().Get(facet_type->facet_type_id);
         // Witness that `T` implements the `*assoc_interface`.
         SemIR::InstId witness_inst_id = SemIR::InstId::None;
-        for (auto base_interface : facet_type_info.impls_constraints) {
+        // TODO: This assumes `impls_constraints` are in the same order as
+        // `CompleteFacetType::required_interfaces`, but there may be more
```
Comment (josh11b) [inline toolchain/check/member_access.cpp]:
```suggestion
        // `CompleteFacetType::required_interfaces`, but once we add
        // support for named constraints there may be more
```

File: toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon [hunk 6]
```diff
@@ -66,28 +66,14 @@ fn G[T:! A & Empty & B](t: T) {
   // CHECK:STDERR:   ^~~~~~~~
   // CHECK:STDERR:
   T.(A.AA)();
-  // CHECK:STDERR: fail_todo_call_combined_impl_witness.carbon:[[@LINE+7]]:3: error: cannot access member of interface `B` in type `Empty & A & B` that does not implement that interface [MissingImplInMemberAccess]
+  // CHECK:STDERR: fail_todo_call_combined_impl_witness.carbon:[[@LINE+4]]:3: error: cannot access member of interface `B` in type `Empty & A & B` that does not implement that interface [MissingImplInMemberAccess]
```
Comment (josh11b) [inline toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon]: Why do we still get these errors?

File: toolchain/check/impl_lookup.cpp (hunk 1 above)
Comment (danakj) [reply toolchain/check/impl_lookup.cpp]: Done

File: toolchain/check/impl_lookup.h (hunk 4 above)
Comment (danakj) [reply toolchain/check/impl_lookup.h]: Done

File: toolchain/check/impl_lookup.h (hunk 3 above)
Comment (danakj) [reply toolchain/check/impl_lookup.h]: Yes that's right, an error may even mean that the inputs were errors, which is why it says a diagnostic may have already been produced before.

File: toolchain/check/impl_lookup.h (hunk 2 above)
Comment (danakj) [reply toolchain/check/impl_lookup.h]: Done

File: toolchain/check/member_access.cpp (hunk 5 above)
Comment (danakj) [reply toolchain/check/member_access.cpp]: Reworded to say that we require the named constraint ones to come later.

File: toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon (hunk 6 above)
Comment (danakj) [reply toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon]: After rebasing on your recent work, the errors are different:

```
  // CHECK:STDERR: fail_todo_call_combined_impl_witness.carbon:[[@LINE+7]]:3: error: cannot implicitly convert value of type `Empty & A & B` to `A` [ImplicitAsConversionFailure]
  // CHECK:STDERR:   T.(A.AA)();
  // CHECK:STDERR:   ^~~~~~~~
```

Not sure why - I can look into it with another PR?

**Review by danakj — COMMENTED** [review]
Thanks, PTAL

File: toolchain/check/impl_lookup.cpp [hunk 7]
```diff
@@ -382,16 +372,14 @@ auto LookupImplWitness(Context& context, SemIR::LocId loc_id,
...
-    // GetInterfacesFromConstantId.
-    return SemIR::InstBlockId::None;
-  }
+      context, query_facet_type_const_id, has_other_requirements);
   if (has_other_requirements) {
     // TODO: Remove this when other requirements go away.
     return SemIR::InstBlockId::None;
   }
+  if (interfaces.empty()) {
+    return SemIR::InstBlockId::None;
```
Comment (josh11b) [inline toolchain/check/impl_lookup.cpp]:
```suggestion
    return SemIR::InstBlockId::Empty;
```

File: toolchain/check/impl_lookup.h (hunk 3 above)
Comment (josh11b) [reply toolchain/check/impl_lookup.h]:
```suggestion
// - An error value, indicating the program is invalid and a diagonstic has been
```

File: toolchain/check/impl_lookup.h [hunk 8]
```diff
@@ -15,9 +15,9 @@ namespace Carbon::Check {
...
 // The return value is one of:
-// - A non-empty InstBlockId value, containing an `ImplWitness` instruction for
-//   each required interface in the `query_facet_type_const_id`. This verifies
-//   the facet type is satisfied for the type in `type_const_id`, and provides a
+// - An InstBlockId value, containing an `ImplWitness` instruction for each
+//   required interface in the `query_facet_type_const_id`. This verifies the
+//   facet type is satisfied for the type in `type_const_id`, and provides a
 //   witness for accessing the impl of each interface.
 //
 // - `InstBlockId::None`, indicating lookup failed for at least one required
```
Comment (josh11b) [inline toolchain/check/impl_lookup.h:23]: Maybe say explicitly that no diagnostic has been issued?

File: toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon (hunk 6 above)
Comment (josh11b) [reply toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon]: Another PR is fine.

File: toolchain/check/impl_lookup.h (hunk 8 above)
Comment (danakj) [reply toolchain/check/impl_lookup.h:23]: Done

File: toolchain/check/impl_lookup.h (hunk 3 above)
Comment (danakj) [reply toolchain/check/impl_lookup.h]: Done

File: toolchain/check/impl_lookup.cpp (hunk 7 above)
Comment (danakj) [reply toolchain/check/impl_lookup.cpp]: Done

File: toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon (hunk 6 above)
Comment (danakj) [reply toolchain/check/testdata/facet/no_prelude/fail_todo_call_combined_impl_witness.carbon]: These now pass in https://github.com/carbon-language/carbon-lang/pull/5085

**Review by josh11b — APPROVED** [review]
