### ISSUE TITLE
Can't have negative floats

### ISSUE THREAD

**Issue by wolffg** [carbon-language/carbon-lang#7159]
### Description of the bug:

Tried to subtract a float from a float, or have a negative float, and it errored out.

### What did you do, or what's a simple way to reproduce the bug?

https://carbon.compiler-explorer.com/z/fPGeeqvj8

### What did you expect to happen?

Have a negative value, or do subtraction.

### What actually happened?

<source>:8:55: error: cannot access member of interface `Core.Negate` in type `Core.FloatLiteral` that does not implement that interface
var ne_point: AnInitializeablePoint = {.x = 1.0, .y = -1.0};
                                                      ^~~~

<source>:9:46: error: cannot access member of interface `Core.SubWith(Core.FloatLiteral)` in type `Core.FloatLiteral` that does not implement that interface
var sw_point: AnInitializeablePoint = {.x = (0.0 - 1.0), .y = 1.0};
                                             ^~~~~~~~~

### Any other information, logs, or outputs that you want to share?

```
class AnInitializeablePoint {
 var x: f64;
 var y: f64;
}

var ne_point: AnInitializeablePoint = {.x = 1.0, .y = -1.0};
var sw_point: AnInitializeablePoint = {.x = (0.0 - 1.0), .y = 1.0};
```

**Comment by DavidLoftus** [comment]
Doesn't seem to be specific to negation / subtraction, AddWith() is also missing.

Atleast from what I can tell this is likely a regression since https://github.com/carbon-language/carbon-lang/pull/5944 which restricted the impl to sized floats, the change does seem somewhat intentional, unsure if maybe there's TODO somewhere to address it already.

Way I see it probably 2 approaches to fix:

- Update the builtin back to accepting any Float and specialcasing FloatLiteral within Check / Lower.
- Make a new impl (with its own builtin) for handling binary operations involving FloatLiteral

One thing I'm not sure of is handling imprecision of binary operators, especially since RealId can represent a base 10 float or a base 2 float, e.g. how should `1.1 + 0x1.1` behave, if we want to retain precision we would promote 0x1.1 to be represented in base 10. Is this complexity we want to add to toolchain or would we just drop requirement of precision and cast to f64 when evaluation const / lowering.

**Comment by jaswanthsanjay88** [comment]
assign the issue for me

**Comment by danakj** [comment]
> assign the issue for me

Feel free to submit a PR. I would suggest starting small - with a single operation at a time.

**Comment by jaswanthsanjay88** [comment]
> > assign the issue for me
> 
> Feel free to submit a PR. I would suggest starting small - with a single operation at a time.

Ok, Thank you For info

**Comment by abhinav-phi** [comment]
I'd like to take the next operation: `FloatLiteral` still only implements `Negate`, `AddWith`, and `SubWith` on trunk (see `core/prelude/operators/arithmetic.carbon`), so `var x: f64 = 2.0 * 1.0;` still errors. Following the pattern of #7616/#7621, I'd implement a `float.mul` builtin for `FloatLiteralValue`s plus `impl FloatLiteral as MulWith(Self)`, literals-only folding, with check/lower tests mirroring the `float_literal/add` testdata.
One question before I touch division: for `DivWith`, what should constant folding do about `1.0 / 0.0` (and `-1.0 / 0.0`) — fold to IEEE infinities, or diagnose? I'd rather land multiplication first and handle the division policy as a separate small PR once there's a preference.

**Comment by DavidLoftus** [comment]
since intliterals are intended to be compile time only, I would expect any division by zero to diagnose.

W.r.t float.div note discussion from few months back: https://discord.com/channels/655572317891461132/655578254970716160/1508945399296294922

Implementing division without loss of precision would require updating Real to use a rational representation

**Comment by abhinav-phi** [comment]
Hi, following up on the multiplication scope for this issue.

`FloatLiteral` still implements only `Negate`, `AddWith`, and `SubWith` on trunk, so a declaration like `var x: f64 = 2.0 * 1.0;` still fails to check. I opened a focused multiplication PR here: https://github.com/carbon-language/carbon-lang/pull/7797

It adds the `float.mul` builtin for literals with exact constant folding plus `MulWith` and check tests mirroring the addition pattern. Division is deliberately left out for now, pending maintainer preference on zero-division handling.

One honest limitation: Bazel is not available in my environment, so local tests are not run and CI results are needed before merge. Thanks.

**Comment by chandlerc** [comment]
> One honest limitation: Bazel is not available in my environment, so local tests are not run and CI results are needed before merge. Thanks.

Sorry, but it isn't reasonable to try to contribute if you can't use our contributing tools. Building and running the toolchain yourself is essential to become a productive contributor to Carbon. Operating an AI tool to make a contribution _without_ that set up tool isn't a great way to learn about and develop as a Carbon contributor, and isn't a good use of our time as a project.

I've closed the PR for now.
